### ISSUE TITLE
re-cli

### ISSUE THREAD

**Issue by idkjs** [softwarefactory-project/re-patternfly#1]
Greetings @sf-project-io,

Thanks for sharing this project.

I though I would hack on it and would like to know how to get https://softwarefactory-project.io/cgit/software-factory/re-cli/

Thank you.

**Comment by TristanCacqueray** [comment]
Hi @idkjs, you can clone that url, e.g. `git clone https://softwarefactory-project.io/cgit/software-factory/re-cli/`. Otherwise the project is now replicated on github at: https://github.com/softwarefactory-project/re-cli .

**Comment by idkjs** [comment]
Tried that yesterday but could not get it to go. Thanks for the update.

**Comment by idkjs** [comment]
While I was on the softwarefactory site I thought I might try to set it up on my machine. You couldn't point me to a good document that might show how to set up on a mac, could you?

Thanks again.

**Comment by TristanCacqueray** [comment]
You would have to use a virtual machine, here is the quickstart documentation: https://docs.softwarefactory-project.io/sf-config-3.5/operator/quickstart.html
